package com.jake.duolauncher

internal fun launcherFormat(id: Int, vararg args: Any): String =
    requireNotNull(DuoApplication.uiResources).getString(id, *args)

/** Resource-backed bridge for legacy UI callbacks that cannot call stringResource. */
internal fun launcherText(english: String): String {
    val resources = DuoApplication.uiResources ?: return english
    return launcherStringIds[english]?.let(resources::getString) ?: english
}

private val launcherStringIds = mapOf(
    "Back" to R.string.legacy_ui_0,
    "Done" to R.string.legacy_ui_1,
    "Cancel" to R.string.legacy_ui_2,
    "Apply" to R.string.legacy_ui_3,
    "OK" to R.string.legacy_ui_4,
    "Save" to R.string.legacy_ui_5,
    "Restore" to R.string.legacy_ui_6,
    "Resume" to R.string.legacy_ui_7,
    "Remove" to R.string.legacy_ui_8,
    "Replace" to R.string.legacy_ui_9,
    "Reconnect" to R.string.legacy_ui_10,
    "Personal" to R.string.legacy_ui_11,
    "Work" to R.string.legacy_ui_12,
    "Widgets" to R.string.legacy_ui_13,
    "Wallpaper" to R.string.legacy_ui_14,
    "Close app options" to R.string.legacy_ui_15,
    "Close empty space options" to R.string.legacy_ui_16,
    "Move to first position" to R.string.legacy_ui_17,
    "Move earlier" to R.string.legacy_ui_18,
    "Move later" to R.string.legacy_ui_19,
    "Move on Home" to R.string.legacy_ui_20,
    "Add to Home" to R.string.legacy_ui_21,
    "Create folder" to R.string.legacy_ui_22,
    "App info" to R.string.legacy_ui_23,
    "Remove from Home" to R.string.legacy_ui_24,
    "Customize launcher" to R.string.legacy_ui_25,
    "Choose what belongs in this space." to R.string.legacy_ui_26,
    "Search apps" to R.string.legacy_ui_27,
    "Clear search" to R.string.legacy_ui_28,
    "Turn on work apps" to R.string.legacy_ui_29,
    "Folder name" to R.string.legacy_ui_30,
    "Move to dock" to R.string.legacy_ui_31,
    "Remove shortcut" to R.string.legacy_ui_32,
    "Widgets page" to R.string.legacy_ui_33,
    "All apps page" to R.string.legacy_ui_34,
    "All apps" to R.string.legacy_ui_35,
    "New home page" to R.string.legacy_ui_36,
    "Back to home" to R.string.legacy_ui_37,
    "Back to widgets" to R.string.legacy_ui_38,
    "Replace here" to R.string.legacy_ui_39,
    "Previous home page" to R.string.legacy_ui_40,
    "Next home page" to R.string.legacy_ui_41,
    "Place" to R.string.legacy_ui_42,
    "Ready to place" to R.string.legacy_ui_43,
    "No room here" to R.string.legacy_ui_44,
    "Dock full • Move an app out first" to R.string.legacy_ui_45,
    "Drag to resize widget" to R.string.legacy_ui_46,
    "Move this widget into the six-row grid before resizing." to R.string.legacy_ui_47,
    "Layout document" to R.string.legacy_ui_48,
    "The system document picker is still open. Return to it to finish, or cancel this operation." to R.string.legacy_ui_49,
    "Background photo" to R.string.legacy_ui_50,
    "The photo picker was interrupted. Resume choosing a photo, or cancel and keep the current background." to R.string.legacy_ui_51,
    "Layout backup problem" to R.string.legacy_ui_52,
    "Layout backup" to R.string.legacy_ui_53,
    "Widget not added" to R.string.legacy_ui_54,
    "Finish widget setup" to R.string.legacy_ui_55,
    "The widget is waiting at its chosen spot. Finish setup to add it, or cancel to remove the placeholder." to R.string.legacy_ui_56,
    "Continue widget setup" to R.string.legacy_ui_57,
    "Finish setup" to R.string.legacy_ui_58,
    "Cancel widget setup" to R.string.legacy_ui_59,
    "Widget settings" to R.string.legacy_ui_60,
    "Widget settings were interrupted. Resume configuration, or cancel and keep the widget unchanged." to R.string.legacy_ui_61,
    "Clock" to R.string.legacy_ui_62,
    "Date" to R.string.legacy_ui_63,
    "Widget panel" to R.string.legacy_ui_64,
    "Home options" to R.string.legacy_ui_65,
    "Clock widget; tap to replace" to R.string.legacy_ui_66,
    "Local time" to R.string.legacy_ui_67,
    "A little more room." to R.string.legacy_ui_68,
    "Add a calendar, photos, or another widget." to R.string.legacy_ui_69,
    "Add widget" to R.string.legacy_ui_70,
    "Device overview" to R.string.legacy_ui_71,
    "Charging" to R.string.legacy_ui_72,
    "Your widgets" to R.string.legacy_ui_73,
    "Tap to choose" to R.string.legacy_ui_74,
    "Leave this position empty" to R.string.legacy_ui_75,
    "No apps found" to R.string.legacy_ui_76,
    "Widget options" to R.string.legacy_ui_77,
    "Close widget options" to R.string.legacy_ui_78,
    "Resize" to R.string.legacy_ui_79,
    "Resize on Home" to R.string.legacy_ui_80,
    "Width" to R.string.legacy_ui_81,
    "Height" to R.string.legacy_ui_82,
    "Decrease widget width" to R.string.legacy_ui_83,
    "Increase widget width" to R.string.legacy_ui_84,
    "Decrease widget height" to R.string.legacy_ui_85,
    "Increase widget height" to R.string.legacy_ui_86,
    "Sizes that overlap another item are ignored." to R.string.legacy_ui_87,
    "That size overlaps another item or extends beyond the page." to R.string.legacy_ui_88,
    "Apply size" to R.string.legacy_ui_89,
    "Search widgets" to R.string.legacy_ui_90,
    "Turn on" to R.string.legacy_ui_91,
    "2 × 2 · Tap to place" to R.string.legacy_ui_92,
    "Doesn’t fit this layout" to R.string.legacy_ui_93,
    "Tap to place · Hold to drag" to R.string.legacy_ui_94,
    "No widgets found" to R.string.legacy_ui_95,
    "There isn’t room for this size. Choose another page or move an item first." to R.string.legacy_ui_96,
    "There isn’t room for this card. Choose another page or move an item first." to R.string.legacy_ui_97,
    "There isn’t room there. Try another space or page." to R.string.legacy_ui_98,
    "The widget host returned an unexpected binding. Try again." to R.string.legacy_ui_99,
    "Finish or cancel the open widget settings first." to R.string.legacy_ui_100,
    "This widget could not be added. Try another widget." to R.string.legacy_ui_101,
    "This widget can no longer be configured." to R.string.legacy_ui_102,
    "This widget could not open its settings." to R.string.legacy_ui_103,
    "There isn't room for this widget here." to R.string.legacy_ui_104,
    "Home changed while the widget was being configured. Choose a space again." to R.string.legacy_ui_105,
    "Shade gestures are starting. Swipe down again." to R.string.legacy_ui_106,
    "Android couldn’t open the system panel." to R.string.legacy_ui_107,
    "Accessibility settings are unavailable." to R.string.legacy_ui_108,
    "Calendar" to R.string.legacy_ui_109,
    "Weather" to R.string.legacy_ui_110,
    "Today’s agenda" to R.string.legacy_ui_111,
    "Device battery" to R.string.legacy_ui_112,
    "Map" to R.string.legacy_ui_113,
    "Tap to add an app widget" to R.string.legacy_ui_114,
    "Tap to choose a widget" to R.string.legacy_ui_115,
    "This device · Charging" to R.string.legacy_ui_116,
    "This device battery" to R.string.legacy_ui_117,
    "Battery ring" to R.string.legacy_ui_118,
)
